# Generated by Django 5.2 on 2025-04-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='completed', max_length=10),
            preserve_default=False,
        ),
    ]
