# Generated by Django 5.2 on 2025-04-20 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('origin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('seats_available', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['number'], name='search_trai_number_8248d0_idx'), models.Index(fields=['origin_date'], name='search_trai_origin__e66e7f_idx')],
                'unique_together': {('number', 'origin_date')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField()),
                ('distance_from_src', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stop_order', models.PositiveIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='search.train')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('train', 'station'), ('train', 'stop_order')},
            },
        ),
    ]
