# Generated by Django 5.2 on 2025-04-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
