# Generated by Django 5.2 on 2025-04-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_schedule_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='arrival_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
