# Generated by Django 5.2 on 2025-04-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_schedule_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='arrival_datetime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='departure_datetime',
        ),
        migrations.AddField(
            model_name='schedule',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
