# Generated by Django 5.2 on 2025-04-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_schedule_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
